name: Updoc

on:
  workflow_call:
    inputs:
      familypacks:
        description: 'Family packages to be published(except monolith)'
        default: ''
        required: false
        type: string
    secrets:
      UPBOUND_CI_PROD_BUCKET_SA:
        required: true

env:
  GO_VERSION: '1.19'

jobs:
  publish-docs:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2
        with:
          submodules: true

      - name: Setup Go
        uses: actions/setup-go@bfdd3570ce990073878bf10f6b2d79082de49492 # v2
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Find the Go Build Cache
        id: go
        run: echo "cache=$(make go.cachedir)" >> $GITHUB_OUTPUT

      - name: Cache the Go Build Cache
        uses: actions/cache@88522ab9f39a2ea568f7027eddc7d8d8bc9d59c8 # v3
        with:
          path: ${{ steps.go.outputs.cache }}
          key: ${{ runner.os }}-build-updoc-artifacts-${{ hashFiles('**/go.sum') }}
          restore-keys: ${{ runner.os }}-build-updoc-artifacts-

      - name: Cache Go Dependencies
        uses: actions/cache@88522ab9f39a2ea568f7027eddc7d8d8bc9d59c8 # v3
        with:
          path: .work/pkg
          key: ${{ runner.os }}-updoc-pkg-${{ hashFiles('**/go.sum') }}
          restore-keys: ${{ runner.os }}-updoc-pkg-

      - name: Create Service Account File
        env:
          GAC: ${{ secrets.UPBOUND_CI_PROD_BUCKET_SA }}
        run: |
          echo "${GAC}" > sa.json

      - name: Upload Docs
        env:
          GOOGLE_APPLICATION_CREDENTIALS: sa.json
          PROVIDER_NAME: ${GITHUB_REPOSITORY#*/}
          VER_MAJOR_MINOR: v${GITHUB_REF#"refs/heads/release-"}
          FAMILYPACKS: ${{ inputs.familypacks }}
        run: |
          if [[ "${GITHUB_REF##*/}" == release-* ]]; then
            for f in $SUBPACKAGES; do
              echo "Publishing Docs for ${{ env.PROVIDER_NAME }}, ${{ env.VER_MAJOR_MINOR }}"
              echo go run github.com/upbound/uptest/cmd/updoc@${{ env.UPTEST_VERSION }} upload --docs-dir=./docs --name=${{ env.PROVIDER_NAME }} --version=${{ env.VER_MAJOR_MINOR }} --bucket-name=bucket-marketplace-docs-production --cdn-domain=https://user-content.upbound.io
              echo go run github.com/upbound/uptest/cmd/updoc@${{ env.UPTEST_VERSION }} upload --docs-dir=./docs --name=${{ env.PROVIDER_NAME }}-$f --version=${{ env.VER_MAJOR_MINOR }} --bucket-name=bucket-marketplace-docs-production --cdn-domain=https://user-content.upbound.io
            done
          else
            echo "This job can only be run on release branches"
            exit 1
          fi

